//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snapshot_Maker
{
    using System;
    using System.Collections.Generic;
    
    public partial class frtb
    {
        public int id { get; set; }
        public string uid { get; set; }
        public string groupid { get; set; }
        public string userinfo { get; set; }
        public string username { get; set; }
        public byte[] front { get; set; }
        public byte[] back { get; set; }
        public byte[] left { get; set; }
        public byte[] right { get; set; }
        public Nullable<int> age { get; set; }
        public string gender { get; set; }
        public string race { get; set; }
        public Nullable<int> glasses { get; set; }
    }
}
